apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: awesomeapps
spec:
  containers:
    - name: foo
      image: janedoe/awesomeapp:v1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  imagePullSecrets:
    - name: myregistrykey
