apiVersion: v1
kind: Pod
metadata:
  name: private-image-test-1
spec:
  containers:
    - name: uses-private-image
      image: nginx
      imagePullPolicy: Always
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"    
      command: [ "echo", "SUCCESS" ]