apiVersion: v1
kind: Pod
metadata:
  name: my-nginx1
  labels:
    name: my-nginx
spec:
  containers:
  - name: my-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        hostPort: 8080
