apiVersion: v1
kind: Pod
metadata:
  name: spring-pod4
spec:
  containers:
  - image: chkrishna/springdemoapp:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    name: spring-demoappv2
    ports:
    - containerPort: 8080
      hostPort: 9090
      protocol: TCP