apiVersion: v1
kind: Pod
metadata:
  name: spring-pod43
spec:
  containers:
  - image: chkrishna/springdemoapp:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    name: spring-demoapp
    ports:
    - containerPort: 8082
      protocol: TCP
  